#!/usr/bin/env ruby

fail ArgumentError, "Usage:  prepinch [prefix] [match]\n" if ARGV.count < 2

prefix = ARGV[0]
files = ARGV[1..ARGV.count]

files.each do |name|
  new_name = name.gsub(prefix, '')
  `mv #{name} #{new_name}`
  puts "#{name} ==> #{new_name}"
end
