#!/usr/bin/env ruby

fail ArgumentError, "Usage:  prepinch [prefix]\n" if ARGV.count == 0

prefix = ARGV[0]
files=`ls`.split(/\n/)
files.each do |name|
  new_name = name.gsub(prefix, '')
  `mv #{name} #{new_name}`
  puts "#{name} ==> #{new_name}#"
end
